spring:
  datasource:
    order:
      url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
    inventory:
      url: jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.modulith: DEBUG
